name: actions
on:
  push:
    branches:
      - master
    paths:
      - containers/**
      - .github/workflows/actions.yml
      - "*.sh"
  pull_request:
    branches:
      - master
    paths:
      - containers/**
      - .github/workflows/actions.yml
      - "*.sh"
jobs:
  qemu-user-static:
    runs-on: ubuntu-latest
    env:
      VERSION: 7.2.0-1-b1
      ORIGIN_VERSION: 7.2+dfsg-1+b1
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get repository name
        uses: actions/github-script@v1
        id: repository_name
        with:
          script: |
            return context.repo.repo
          result-encoding: string
      - name: Set variables
        run: |
          echo "DOCKER_REPO=docker.io/${{ secrets.DOCKER_USERNAME }}/${{ steps.repository_name.outputs.result }}" >> $GITHUB_ENV
      - name: Build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          ./run.sh -t "${{ env.VERSION }}" -d "${{ env.DOCKER_REPO }}" -x linux/amd64
      - name: Test
        run: ./test.sh -d "${{ env.DOCKER_REPO }}"
      - name: Push multi-arch
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          ./run.sh -t "${{ env.VERSION }}" -d "${{ env.DOCKER_REPO }}" -p
